#!/usr/bin/env bash
# Shared path defaults for observability GitOps scripts.
# Override any value by exporting the variable before running scripts.

if [[ -z "${REPO_ROOT:-}" ]]; then
  REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
fi

# Repo layout
# These values describe files owned by Git. Promote/install scripts copy from
# here into runtime paths instead of editing these defaults in place.
OBS_REPO_PROMETHEUS_DIR="${OBS_REPO_PROMETHEUS_DIR:-$REPO_ROOT/prometheus}"
OBS_REPO_RULES_DIR="${OBS_REPO_RULES_DIR:-$OBS_REPO_PROMETHEUS_DIR/rules}"
OBS_REPO_PROM_CONFIG="${OBS_REPO_PROM_CONFIG:-$OBS_REPO_PROMETHEUS_DIR/prometheus.yml}"

OBS_REPO_MIMIR_DIR="${OBS_REPO_MIMIR_DIR:-$REPO_ROOT/mimir}"
OBS_REPO_MIMIR_CONFIG="${OBS_REPO_MIMIR_CONFIG:-$OBS_REPO_MIMIR_DIR/mimir-local.yaml}"
OBS_REPO_MIMIR_UNIT="${OBS_REPO_MIMIR_UNIT:-$OBS_REPO_MIMIR_DIR/systemd/mimir.service}"

OBS_REPO_TELEGRAF_DIR="${OBS_REPO_TELEGRAF_DIR:-$REPO_ROOT/telegraf}"
OBS_REPO_TELEGRAF_MAIN="${OBS_REPO_TELEGRAF_MAIN:-$OBS_REPO_TELEGRAF_DIR/telegraf.conf}"
OBS_REPO_TELEGRAF_D="${OBS_REPO_TELEGRAF_D:-$OBS_REPO_TELEGRAF_DIR/telegraf.d}"

OBS_REPO_GRAFANA_DIR="${OBS_REPO_GRAFANA_DIR:-$REPO_ROOT/grafana}"
OBS_REPO_DASH_DEV_DIR="${OBS_REPO_DASH_DEV_DIR:-$OBS_REPO_GRAFANA_DIR/dashboards-dev}"
OBS_REPO_DASH_PROD_DIR="${OBS_REPO_DASH_PROD_DIR:-$OBS_REPO_GRAFANA_DIR/dashboards-prod}"
OBS_REPO_GRAFANA_DASHBOARDS_PROVISIONING_DIR="${OBS_REPO_GRAFANA_DASHBOARDS_PROVISIONING_DIR:-$OBS_REPO_GRAFANA_DIR/provisioning/dashboards}"
OBS_REPO_GRAFANA_DATASOURCES_DIR="${OBS_REPO_GRAFANA_DATASOURCES_DIR:-$OBS_REPO_GRAFANA_DIR/provisioning/datasources}"

OBS_REPO_SYSTEMD_OVERRIDES_DIR="${OBS_REPO_SYSTEMD_OVERRIDES_DIR:-$REPO_ROOT/systemd-overrides}"
OBS_REPO_GRAFANA_SYSTEMD_DIR="${OBS_REPO_GRAFANA_SYSTEMD_DIR:-$OBS_REPO_SYSTEMD_OVERRIDES_DIR/grafana-server.service.d}"
OBS_REPO_RUNTIME_DIR="${OBS_REPO_RUNTIME_DIR:-$REPO_ROOT/runtime}"
OBS_REPO_PROM_SYSTEMD_DIR="${OBS_REPO_PROM_SYSTEMD_DIR:-$OBS_REPO_SYSTEMD_OVERRIDES_DIR/prometheus.service.d}"

OBS_REPO_ALLOY_DIR="${OBS_REPO_ALLOY_DIR:-$REPO_ROOT/alloy}"
OBS_REPO_ALLOY_PROD_CFG="${OBS_REPO_ALLOY_PROD_CFG:-$OBS_REPO_ALLOY_DIR/prod/config.alloy}"
OBS_REPO_ALLOY_CANARY_CFG="${OBS_REPO_ALLOY_CANARY_CFG:-$OBS_REPO_ALLOY_DIR/canary/config.alloy}"
OBS_REPO_ALLOY_CANARY_UNIT="${OBS_REPO_ALLOY_CANARY_UNIT:-$OBS_REPO_ALLOY_DIR/systemd/alloy-canary.service}"

# Runtime layout (Linux host)
# These host paths are touched by promote/install scripts. Keeping them in one
# sourced file prevents drift across operational scripts.
OBS_RUNTIME_PROM_RULES_DIR="${OBS_RUNTIME_PROM_RULES_DIR:-/etc/prometheus/rules}"
OBS_RUNTIME_PROM_CONFIG="${OBS_RUNTIME_PROM_CONFIG:-/etc/prometheus/prometheus.yml}"

OBS_RUNTIME_MIMIR_CONFIG_DIR="${OBS_RUNTIME_MIMIR_CONFIG_DIR:-/etc/mimir}"
OBS_RUNTIME_MIMIR_CONFIG="${OBS_RUNTIME_MIMIR_CONFIG:-$OBS_RUNTIME_MIMIR_CONFIG_DIR/mimir.yaml}"
OBS_RUNTIME_MIMIR_UNIT="${OBS_RUNTIME_MIMIR_UNIT:-/etc/systemd/system/mimir.service}"
OBS_RUNTIME_MIMIR_DATA_DIR="${OBS_RUNTIME_MIMIR_DATA_DIR:-/var/lib/prometheus/mimir}"
OBS_RUNTIME_MIMIR_USER="${OBS_RUNTIME_MIMIR_USER:-prometheus}"
OBS_RUNTIME_MIMIR_GROUP="${OBS_RUNTIME_MIMIR_GROUP:-prometheus}"
OBS_RUNTIME_PROM_SYSTEMD_DIR="${OBS_RUNTIME_PROM_SYSTEMD_DIR:-/etc/systemd/system/prometheus.service.d}"

OBS_RUNTIME_TELEGRAF_DIR="${OBS_RUNTIME_TELEGRAF_DIR:-/etc/telegraf}"
OBS_RUNTIME_TELEGRAF_MAIN="${OBS_RUNTIME_TELEGRAF_MAIN:-$OBS_RUNTIME_TELEGRAF_DIR/telegraf.conf}"
OBS_RUNTIME_TELEGRAF_D="${OBS_RUNTIME_TELEGRAF_D:-$OBS_RUNTIME_TELEGRAF_DIR/telegraf.d}"

OBS_RUNTIME_DASH_DEV_DIR="${OBS_RUNTIME_DASH_DEV_DIR:-/var/lib/grafana/dashboards-dev}"
OBS_RUNTIME_DASH_PROD_DIR="${OBS_RUNTIME_DASH_PROD_DIR:-/var/lib/grafana/dashboards-prod}"
OBS_RUNTIME_GRAFANA_DB="${OBS_RUNTIME_GRAFANA_DB:-/var/lib/grafana/grafana.db}"
OBS_RUNTIME_GRAFANA_PROVISIONING_DIR="${OBS_RUNTIME_GRAFANA_PROVISIONING_DIR:-/etc/grafana/provisioning}"
OBS_RUNTIME_GRAFANA_DASHBOARDS_PROVISIONING_DIR="${OBS_RUNTIME_GRAFANA_DASHBOARDS_PROVISIONING_DIR:-$OBS_RUNTIME_GRAFANA_PROVISIONING_DIR/dashboards}"
OBS_RUNTIME_GRAFANA_DATASOURCES_DIR="${OBS_RUNTIME_GRAFANA_DATASOURCES_DIR:-$OBS_RUNTIME_GRAFANA_PROVISIONING_DIR/datasources}"
OBS_RUNTIME_GRAFANA_SYSTEMD_DIR="${OBS_RUNTIME_GRAFANA_SYSTEMD_DIR:-/etc/systemd/system/grafana-server.service.d}"

OBS_RUNTIME_ALLOY_DIR="${OBS_RUNTIME_ALLOY_DIR:-/etc/alloy}"
OBS_RUNTIME_ALLOY_PROD_CFG="${OBS_RUNTIME_ALLOY_PROD_CFG:-$OBS_RUNTIME_ALLOY_DIR/config.alloy}"
OBS_RUNTIME_ALLOY_CANARY_CFG="${OBS_RUNTIME_ALLOY_CANARY_CFG:-$OBS_RUNTIME_ALLOY_DIR/config-canary.alloy}"
OBS_RUNTIME_ALLOY_CANARY_UNIT="${OBS_RUNTIME_ALLOY_CANARY_UNIT:-/etc/systemd/system/alloy-canary.service}"
